import { StyleSheet, Platform } from 'react-native';

const COLORS = {
  primary: '#FE724C',
  white: '#FFFFFF',
  textDark: '#1A1E26',
  textLight: '#9796A1',
  bgLight: '#F3F4F6',
  borderLine: '#F2F2F2',
  onlineGreen: '#4CD964',
  avatarBg: '#9DA8B6',
  imgPlaceholder: '#9DA8B6',
  declineBorder: '#E3E5E9',
  sparkline: '#FFD3C2',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 50 : 60,
    paddingBottom: 110,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.bgLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconText: {
    fontSize: 18,
    color: COLORS.textDark,
  },
  avatarButton: {
    position: 'relative',
  },
  avatarPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.avatarBg,
  },
  avatarOnlineDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.onlineGreen,
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  statusCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.textDark,
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 18,
    marginBottom: 18,
  },
  statusTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.white,
    marginBottom: 4,
  },
  statusSubtitle: {
    fontSize: 12,
    color: '#B7BCC4',
  },
  statsRow: {
    flexDirection: 'row',
    marginBottom: 18,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.bgLight,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginRight: 12,
  },
  statNumber: {
    fontSize: 26,
    fontWeight: '900',
    color: COLORS.textDark,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textLight,
    letterSpacing: 0.5,
  },
  earningsCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.borderLine,
    padding: 18,
    marginBottom: 24,
  },
  earningsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  earningsLabel: {
    fontSize: 14,
    color: COLORS.textLight,
  },
  seeDetails: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.primary,
  },
  earningsAmount: {
    fontSize: 26,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginBottom: 14,
  },
  sparklineRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 70,
  },
  sparklineBar: {
    flex: 1,
    backgroundColor: COLORS.sparkline,
    borderRadius: 4,
    marginRight: 6,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  sectionCount: {
    fontSize: 12,
    color: COLORS.textLight,
  },
  seeAll: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.primary,
  },
  offlineNotice: {
    backgroundColor: COLORS.bgLight,
    borderRadius: 16,
    padding: 18,
    marginBottom: 24,
  },
  offlineNoticeText: {
    fontSize: 13,
    color: COLORS.textLight,
    textAlign: 'center',
    lineHeight: 19,
  },
  requestCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.borderLine,
    padding: 12,
    marginBottom: 12,
  },
  requestImagePlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: COLORS.imgPlaceholder,
    marginRight: 12,
  },
  requestDetails: {
    flex: 1,
    marginRight: 8,
  },
  requestRestaurant: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginBottom: 2,
  },
  requestMeta: {
    fontSize: 11,
    color: COLORS.textLight,
    marginBottom: 2,
  },
  requestItems: {
    fontSize: 11,
    color: COLORS.textLight,
    marginBottom: 4,
  },
  requestPayout: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  requestActions: {
    alignItems: 'stretch',
  },
  acceptButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginBottom: 6,
  },
  acceptButtonText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  declineButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.declineBorder,
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  declineButtonText: {
    color: COLORS.textLight,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  runningCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bgLight,
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
  },
  runningImagePlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: COLORS.imgPlaceholder,
    marginRight: 12,
  },
  runningDetails: {
    flex: 1,
  },
  runningRestaurant: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginBottom: 2,
  },
  runningMeta: {
    fontSize: 11,
    color: COLORS.textLight,
  },
  stageBadge: {
    backgroundColor: '#FFE9E1',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  stageBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.primary,
  },
  historyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#FAFAFA',
  },
  historyImagePlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: COLORS.imgPlaceholder,
    marginRight: 12,
  },
  historyDetails: {
    flex: 1,
  },
  historyRestaurant: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.textDark,
    marginBottom: 2,
  },
  historyMeta: {
    fontSize: 11,
    color: COLORS.textLight,
  },
  historyPayout: {
    fontSize: 13,
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 75,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLine,
    paddingHorizontal: 10,
  },
  navItem: {
    padding: 10,
  },
  navIcon: {
    fontSize: 20,
    color: COLORS.textLight,
  },
  navIconActive: {
    color: COLORS.primary,
  },
  navActionCenter: {
    width: 55,
    height: 55,
    borderRadius: 27.5,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  navActionIcon: {
    fontSize: 20,
  },
});