import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    content: {
        paddingHorizontal: 16,
        paddingBottom: 40,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
    },
    headerTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#222',
    },
    resetText: {
        color: '#F97316',
        fontWeight: '600',
        fontSize: 12,
    },
    label: {
        fontSize: 11,
        fontWeight: '600',
        color: '#999',
        marginTop: 16,
        marginBottom: 8,
        letterSpacing: 0.5,
    },
    input: {
        borderWidth: 1,
        borderColor: '#eee',
        backgroundColor: '#F7F7F7',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
        color: '#333',
    },
    imageRow: {
        flexDirection: 'row',
        gap: 10,
    },
    imageThumbWrapper: {
        width: 70,
        height: 70,
        borderRadius: 8,
        overflow: 'hidden',
    },
    imageThumb: {
        width: '100%',
        height: '100%',
    },
    uploadBox: {
        width: 70,
        height: 70,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#eee',
        borderStyle: 'dashed',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FAFAFA',
    },
    uploadText: {
        fontSize: 11,
        color: '#F97316',
        marginTop: 4,
    },
    imageHint: {
        fontSize: 11,
        color: '#B45309',
        marginTop: 6,
        fontStyle: 'italic',
    },
    priceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    priceInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: '#eee',
        backgroundColor: '#F7F7F7',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
        color: '#333',
    },
    checkboxRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    checkboxLabel: {
        fontSize: 12,
        color: '#555',
    },
    categoryRow: {
        flexDirection: 'row',
        gap: 8,
        flexWrap: 'wrap',
    },
    categoryChip: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#eee',
        backgroundColor: '#F7F7F7',
    },
    categoryChipSelected: {
        backgroundColor: '#F97316',
        borderColor: '#F97316',
    },
    categoryChipText: {
        fontSize: 12,
        color: '#666',
        fontWeight: '600',
    },
    categoryChipTextSelected: {
        color: '#fff',
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 18,
        marginBottom: 8,
    },
    sectionHeader: {
        fontSize: 13,
        fontWeight: '700',
        color: '#333',
    },
    seeAll: {
        fontSize: 12,
        color: '#999',
    },
    ingredientItem: {
        alignItems: 'center',
        marginRight: 16,
        width: 56,
    },
    ingredientCircle: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#FFF1E8',
        alignItems: 'center',
        justifyContent: 'center',
    },
    ingredientCircleSelected: {
        backgroundColor: '#F97316',
    },
    ingredientLabel: {
        fontSize: 10,
        color: '#666',
        marginTop: 4,
        textAlign: 'center',
    },
    detailsInput: {
        borderWidth: 1,
        borderColor: '#eee',
        backgroundColor: '#F7F7F7',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 13,
        color: '#555',
        textAlignVertical: 'top',
        minHeight: 90,
    },
    saveButton: {
        marginTop: 24,
        backgroundColor: '#F97316',
        borderRadius: 10,
        paddingVertical: 14,
        alignItems: 'center',
    },
    saveButtonText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 14,
        letterSpacing: 0.5,
    },
});