import { StyleSheet, Platform } from 'react-native';

const COLORS = {
  primary: '#FE724C',
  white: '#FFFFFF',
  textDark: '#1A1E26',
  textLight: '#9796A1',
  bgLight: '#F3F4F6',
  borderLine: '#F2F2F2',
  creditGreen: '#2FB672',
  creditGreenBg: '#E6F6EE',
  debitBg: '#FFE9E1',
  error: '#FF3B30',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 50 : 60,
    paddingBottom: 15,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.bgLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.textDark,
  },
  headerSpacer: {
    width: 44,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 110,
  },
  balanceCard: {
    backgroundColor: COLORS.textDark,
    borderRadius: 20,
    padding: 22,
    alignItems: 'center',
    marginBottom: 18,
    marginTop: 5,
  },
  balanceLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#B7BCC4',
    letterSpacing: 1,
    marginBottom: 8,
  },
  balanceAmount: {
    fontSize: 36,
    fontWeight: '900',
    color: COLORS.white,
    marginBottom: 6,
  },
  pendingText: {
    fontSize: 12,
    color: '#B7BCC4',
    marginBottom: 20,
  },
  withdrawButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 40,
    width: '100%',
  },
  withdrawButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  statsRow: {
    flexDirection: 'row',
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.bgLight,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginRight: 12,
  },
  statAmount: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.textLight,
    letterSpacing: 0.5,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginBottom: 12,
  },
  accountCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bgLight,
    borderRadius: 16,
    padding: 14,
  },
  bankIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  bankIcon: {
    fontSize: 18,
  },
  accountBankName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginBottom: 2,
  },
  accountNumber: {
    fontSize: 12,
    color: COLORS.textLight,
    marginBottom: 2,
  },
  accountHolder: {
    fontSize: 11,
    color: COLORS.textLight,
  },
  changeLink: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.primary,
  },
  transactionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#FAFAFA',
  },
  transactionIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  iconWrapCredit: {
    backgroundColor: COLORS.creditGreenBg,
  },
  iconWrapDebit: {
    backgroundColor: COLORS.debitBg,
  },
  transactionIcon: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  transactionDetails: {
    flex: 1,
    marginRight: 8,
  },
  transactionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.textDark,
    marginBottom: 2,
  },
  transactionSubtitle: {
    fontSize: 11,
    color: COLORS.textLight,
    marginBottom: 2,
  },
  transactionDate: {
    fontSize: 10,
    color: COLORS.textLight,
  },
  transactionAmount: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  amountCredit: {
    color: COLORS.creditGreen,
  },
  amountDebit: {
    color: COLORS.primary,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(26,30,38,0.5)',
  },
  modalSheet: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 25,
    paddingTop: 12,
    paddingBottom: 34,
  },
  dragHandle: {
    width: 50,
    height: 5,
    borderRadius: 3,
    backgroundColor: COLORS.bgLight,
    alignSelf: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.textDark,
    textAlign: 'center',
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 12,
    color: COLORS.textLight,
    textAlign: 'center',
    marginBottom: 24,
  },
  amountInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  currencyPrefix: {
    fontSize: 32,
    fontWeight: '900',
    color: COLORS.textDark,
    marginRight: 4,
  },
  amountInput: {
    fontSize: 32,
    fontWeight: '900',
    color: COLORS.textDark,
    minWidth: 100,
    textAlign: 'center',
  },
  availableHint: {
    fontSize: 12,
    color: COLORS.textLight,
    textAlign: 'center',
    marginBottom: 20,
  },
  errorText: {
    fontSize: 12,
    color: COLORS.error,
    textAlign: 'center',
    marginBottom: 12,
    marginTop: -8,
  },
  confirmButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    paddingVertical: 15,
    marginBottom: 10,
  },
  confirmButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  cancelButton: {
    paddingVertical: 10,
  },
  cancelButtonText: {
    color: COLORS.textLight,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
});