import { StyleSheet, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');

const COLORS = {
  primary: '#FE724C',
  textDark: '#323643',
  textLight: '#9796A1',
  textMuted: '#C4C4C4',
  bgLight: '#F3F4F6',
  white: '#FFFFFF',
  lineColor: '#D7D7D7',
  headerDark: '#1A1E26',
  avatarBg: '#9DA8B6',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  mapContainer: {
    ...StyleSheet.absoluteFillObject,
  },
  headerContainer: {
    position: 'absolute',
    top: 50,
    left: 20,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 10,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.headerDark,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  backButtonText: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  headerBadge: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.primary,
    letterSpacing: 1,
    marginBottom: 2,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.headerDark,
  },
  bottomSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: height * 0.72,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 10,
  },
  dragHandle: {
    width: 50,
    height: 5,
    borderRadius: 3,
    backgroundColor: COLORS.bgLight,
    alignSelf: 'center',
    marginBottom: 15,
  },
  scrollContent: {
    paddingHorizontal: 25,
    paddingBottom: 20,
  },
  destinationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bgLight,
    borderRadius: 16,
    padding: 14,
    marginBottom: 15,
  },
  destinationIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  destinationIcon: {
    fontSize: 20,
  },
  destinationName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginBottom: 2,
  },
  destinationAddress: {
    fontSize: 12,
    color: COLORS.textLight,
  },
  orderId: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textLight,
  },
  itemsList: {
    marginBottom: 25,
    paddingLeft: 2,
  },
  itemText: {
    fontSize: 13,
    color: COLORS.textLight,
    marginBottom: 3,
  },
  itemQuantity: {
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  timelineContainer: {
    paddingLeft: 10,
    marginBottom: 10,
  },
  timelineStep: {
    flexDirection: 'row',
    minHeight: 55,
  },
  timelineIconContainer: {
    alignItems: 'center',
    width: 20,
    marginRight: 15,
  },
  dot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: COLORS.textMuted,
    zIndex: 1,
  },
  dotActive: {
    backgroundColor: COLORS.primary,
  },
  line: {
    width: 1,
    flex: 1,
    backgroundColor: COLORS.lineColor,
    marginTop: -2,
    marginBottom: -2,
  },
  lineActive: {
    backgroundColor: COLORS.primary,
  },
  timelineText: {
    fontSize: 14,
    color: COLORS.textLight,
    marginTop: -2,
  },
  textActive: {
    color: COLORS.primary,
    fontWeight: '500',
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textLight,
    letterSpacing: 1,
    marginBottom: 12,
  },
  contactSection: {
    marginBottom: 10,
  },
  contactCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.bgLight,
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
  },
  contactProfileContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  contactAvatarPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.avatarBg,
    marginRight: 12,
  },
  contactName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: COLORS.textDark,
    marginBottom: 3,
  },
  contactRole: {
    fontSize: 12,
    color: COLORS.textLight,
  },
  contactActions: {
    flexDirection: 'row',
  },
  callButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  messageButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  callIcon: {
    fontSize: 14,
  },
  messageIcon: {
    fontSize: 14,
  },
  actionFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 25,
    paddingVertical: 18,
    borderTopWidth: 1,
    borderTopColor: COLORS.bgLight,
    backgroundColor: COLORS.white,
  },
  payoutLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: COLORS.textLight,
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  payoutAmount: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.textDark,
  },
  primaryActionButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 16,
  },
  primaryActionText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '700',
  },
});